/**
 * @file VortexVersion.h
 * @brief Version information for the Vortex API
 * 
 * @note This file is auto-generated by CMake. Do not edit manually.
 */

#ifndef VORTEX_VERSION_H_
#define VORTEX_VERSION_H_

// Version information
#define VORTEX_API_VERSION_MAJOR @VORTEX_API_VERSION_MAJOR@
#define VORTEX_API_VERSION_MINOR @VORTEX_API_VERSION_MINOR@
#define VORTEX_API_VERSION_PATCH @VORTEX_API_VERSION_PATCH@
#define VORTEX_API_VERSION_STRING "@VORTEX_API_VERSION_STRING@"

// Build information
#define VORTEX_API_BUILD_DATE __DATE__
#define VORTEX_API_BUILD_TIME __TIME__

// Feature flags
#define VORTEX_API_FEATURE_DIAGNOSTICS 1
#define VORTEX_API_FEATURE_HEALTH_CHECK 1
#define VORTEX_API_FEATURE_STATISTICS 1

#endif // VORTEX_VERSION_H_ 